{% set name = "polars-upgrade" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/polars_upgrade-{{ version }}.tar.gz
  sha256: 9148baa9c04d3835cfaad2cdf71e7a9fa11c72a60cf346ee7a152861216e379b

build:
  entry_points:
    - polars-upgrade = polars_upgrade._main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - tokenize-rt >=5.2.0

test:
  imports:
    - polars_upgrade
  commands:
    - pip check
    - polars-upgrade --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MarcoGorelli/polars-upgrade
  summary: Automatically upgrade your Polars code so it's compatible with future versions.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - '0xbe7a'
